version: '3.0'
services:
  db:
    image: mysql
    volumes:
            - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: chips
      MYSQL_ROOT_PASSWORD: 1234
    command: 
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile.development
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - DATABASE_URL=mysql://root:1234@db:3306/chips
      - MYSQL_CHARSET=utf8mb4
      - JWT_SECRET=${JWT_SECRET}
      - S3_REGION=${S3_REGION}
      - S3_AWSACCESS_KEY_ID=${S3_AWSACCESS_KEY_ID}
      - S3_AWS_SECRET_ACCESS_KEY=${S3_AWS_SECRET_ACCESS_KEY}
      - CLOUD_FRONT_URL=${CLOUD_FRONT_URL}
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./src/:/src/
    depends_on:
      - db
