version: '3.0'
services:
  nignx:
    image: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot 
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"  
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - server
      - db  
  certbot:
    image: certbot
    restart: unless-stopped
    volumes:
      - ../certbot/conf:/etc/letsencrypt
      - ../certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  db:
    image: mysql
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: 
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - '3306:3306'
  server:
    build:
      context: ./
      dockerfile: ./Dockerfile.development
    environment:
      - NODE_ENV=development
      - PORT=${PORT}
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@db:3306/chips
      - MYSQL_CHARSET=utf8mb4
      - JWT_SECRET=${JWT_SECRET}
      - S3_REGION=${S3_REGION}
      - S3_AWSACCESS_KEY_ID=${S3_AWSACCESS_KEY_ID}
      - S3_AWS_SECRET_ACCESS_KEY=${S3_AWS_SECRET_ACCESS_KEY}
      - CLOUD_FRONT_URL=${CLOUD_FRONT_URL}
      - ADMIN_SIGNUP_SECRET=${ADMIN_SIGNUP_SECRET}
      - ADMIN_JWT_SECRET=${ADMIN_JWT_SECRET}
      - USER_JWT_SECRET=${USER_JWT_SECRET}
    ports:
      - '3000:3000'
    restart: always
    volumes:
      - ./src/:/src/
    depends_on:
      - db
